[fuzzers]
    # sub-tables use "." to connect
    [fuzzers.AFL-Full]
        data_files = [
            "first_crash/full_16157"
        ]
        line_style = "dashed"
        box_color = "xkcd:slate blue"

    [fuzzers.Firm-AFL]
        data_files = [
            "first_crash/firmafl_16157"
        ]
        line_style = "dashdot"
        box_color = "xkcd:olive yellow"

    [fuzzers.EQUAFL]
        data_files = [
            "first_crash/equafl_16157"
        ]
        line_style = "solid"
        box_color = "xkcd:scarlet"

[misc]
    out_dir = "test/out_boxplot"
    file_postfix = "-time-to-exposure"
    project = "bin/boa"
    stat_type = "boxplot"
    notch = false
    plot_title = "/bin/boa (WN2000RPTv1) (s)"
    ylim = [0, 20]