[fuzzers]
    # sub-tables use "." to connect
    [fuzzers.AFL-Full]
        data_files = [
            "first_crash/full_20880"
        ]
        line_style = "dashed"
        box_color = "xkcd:slate blue"

    [fuzzers.Firm-AFL]
        data_files = [
            "first_crash/firmafl_20880"
        ]
        line_style = "dashdot"
        box_color = "xkcd:olive yellow"

    [fuzzers.EQUAFL]
        data_files = [
            "first_crash/equafl_20880"
        ]
        line_style = "solid"
        box_color = "xkcd:scarlet"

[misc]
    out_dir = "test/out_boxplot"
    file_postfix = "-time-to-exposure"
    project = "/sbin/httpd "
    stat_type = "boxplot"
    notch = false
    plot_title = "/sbin/httpd (DIR-825) (s)"
    ylim = [0, 20]